# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  api_key = app_store_connect_api_key(
    key_id: "MAQM3H7TC6",
    issuer_id: "df635863-6723-4797-8034-4280ca4047da",
    key_filepath: "./fastlane/AuthKey_MAQM3H7TC6.p8"
  )
  lane :beta do
    increment_build_number(xcodeproj: "Opiner.xcodeproj")
    build_app(workspace: "Opiner.xcworkspace", scheme: "Opiner Beta")
    pilot
    upload_to_testflight
  end
  lane :prod do
    increment_build_number(xcodeproj: "Opiner.xcodeproj")
    build_app(workspace: "Opiner.xcworkspace", scheme: "Opiner")
    pilot
    upload_to_testflight
  end
end
